apiVersion: v1
kind: Pod
metadata:
  name: topic-table00002
  labels:
    app: topic-table00002
spec:
  restartPolicy: Never
  serviceAccount: pubsub-app
  containers:
  - image: gcr.io/$PROJECT/pubsub-app:202208161316
    name: topic-table00002
    env:
    - name: GOOGLE_CLOUD_PROJECT
      value: $PROJECT
    - name: TOPIC_ID
      value: topic-table00002
    - name: APP_ID
      value: topic-table00002
